<a href="https://colab.research.google.com/github/necmigunduz/ai-learn/blob/main/Learn_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3])
b=np.array([[1,2],[3,4]])

In [26]:
np.zeros((3,8)), np.ones((2,5)), np.eye(3), np.arange(2,10,0.1), np.linspace(1,20,4)

(array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
        3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5,
        4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8,
        5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1,
        7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4,
        8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7,
        9.8, 9.9]),
 array([ 1.        ,  7.33333333, 13.66666667, 20.        ]))

In [27]:
arr=np.array([[1,2,3],[4,5,6]])

In [36]:
print(arr[0,1], arr[:,2])

2 [3 6]


In [41]:
### Array Math
a = np.array([1,2,3])
b = np.array([4,5,6])

In [50]:
print(f'a*b =', a*b)
print(f'a+b =', a+b)
print(f'a-b =', a-b)
print(f'a/b =', a/b)
print(f'a.b =', a.dot(b))

a*b = [ 4 10 18]
a+b = [5 7 9]
a-b = [-3 -3 -3]
a/b = [0.25 0.4  0.5 ]
a.b = 32


In [51]:
## Transpose and Reshape matrix
x = np.array([[1,2],[3,4],[5,6]])

In [65]:
x_reshaped = x.reshape(3,2)
x_transposed = x.T
print(f'x Reshaped', x_reshaped)
print(f'x Transposed', x_transposed)

x Reshaped [[1 2]
 [3 4]
 [5 6]]
x Transposed [[1 3 5]
 [2 4 6]]


In [83]:
random_array = np.random.randint(1,101,size=(1,100))

In [89]:
random_array[0,26]

np.int64(51)

In [91]:
random_array.reshape(10,10)

array([[43, 63, 92,  6, 17, 64, 90, 87, 20, 19],
       [24, 89, 84, 43, 58, 37, 77, 58, 98, 98],
       [81, 56, 86, 51,  8, 65, 51, 68, 60, 29],
       [31, 91, 29, 78,  4, 57, 79,  9, 74, 22],
       [40, 57, 32, 60, 86, 34, 87, 94, 38, 56],
       [46, 55,  5, 80, 16, 79, 23, 54, 80, 93],
       [73, 76, 79, 48, 30, 59, 60, 53, 82, 35],
       [34, 19, 32, 41, 39, 92, 81, 83, 35, 29],
       [96, 21, 77, 79,  6, 21, 44, 62, 38, 98],
       [ 8,  4,  3, 15, 94, 80, 17, 16, 81, 27]])

In [99]:
np.mean(random_array, axis=0)

array([43., 63., 92.,  6., 17., 64., 90., 87., 20., 19., 24., 89., 84.,
       43., 58., 37., 77., 58., 98., 98., 81., 56., 86., 51.,  8., 65.,
       51., 68., 60., 29., 31., 91., 29., 78.,  4., 57., 79.,  9., 74.,
       22., 40., 57., 32., 60., 86., 34., 87., 94., 38., 56., 46., 55.,
        5., 80., 16., 79., 23., 54., 80., 93., 73., 76., 79., 48., 30.,
       59., 60., 53., 82., 35., 34., 19., 32., 41., 39., 92., 81., 83.,
       35., 29., 96., 21., 77., 79.,  6., 21., 44., 62., 38., 98.,  8.,
        4.,  3., 15., 94., 80., 17., 16., 81., 27.])