<a href="https://colab.research.google.com/github/necmigunduz/ai-learn/blob/main/Learn_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a = np.array([1,2,3])
b=np.array([[1,2],[3,4]])

In [ ]:
np.zeros((3,8)), np.ones((2,5)), np.eye(3), np.arange(2,10,0.1), np.linspace(1,20,4)

(array([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
        3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5,
        4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8,
        5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1,
        7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4,
        8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7,
        9.8, 9.9]),
 array([ 1.        ,  7.33333333, 13.66666667, 20.        ]))

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])

In [ ]:
print(arr[0,1], arr[:,2])

2 [3 6]


In [ ]:
### Array Math
a = np.array([1,2,3])
b = np.array([4,5,6])

In [ ]:
print(f'a*b =', a*b)
print(f'a+b =', a+b)
print(f'a-b =', a-b)
print(f'a/b =', a/b)
print(f'a.b =', a.dot(b))

a*b = [ 4 10 18]
a+b = [5 7 9]
a-b = [-3 -3 -3]
a/b = [0.25 0.4  0.5 ]
a.b = 32


In [ ]:
## Transpose and Reshape matrix
x = np.array([[1,2],[3,4],[5,6]])

In [ ]:
x_reshaped = x.reshape(3,2)
x_transposed = x.T
print(f'x Reshaped', x_reshaped)
print(f'x Transposed', x_transposed)

x Reshaped [[1 2]
 [3 4]
 [5 6]]
x Transposed [[1 3 5]
 [2 4 6]]


In [ ]:
random_array = np.random.randint(1,101,size=(1,100))

In [ ]:
random_array[0,26]

np.int64(51)

In [ ]:
random_array.reshape(10,10)

array([[43, 63, 92,  6, 17, 64, 90, 87, 20, 19],
       [24, 89, 84, 43, 58, 37, 77, 58, 98, 98],
       [81, 56, 86, 51,  8, 65, 51, 68, 60, 29],
       [31, 91, 29, 78,  4, 57, 79,  9, 74, 22],
       [40, 57, 32, 60, 86, 34, 87, 94, 38, 56],
       [46, 55,  5, 80, 16, 79, 23, 54, 80, 93],
       [73, 76, 79, 48, 30, 59, 60, 53, 82, 35],
       [34, 19, 32, 41, 39, 92, 81, 83, 35, 29],
       [96, 21, 77, 79,  6, 21, 44, 62, 38, 98],
       [ 8,  4,  3, 15, 94, 80, 17, 16, 81, 27]])

In [ ]:
np.mean(random_array, axis=0)

array([43., 63., 92.,  6., 17., 64., 90., 87., 20., 19., 24., 89., 84.,
       43., 58., 37., 77., 58., 98., 98., 81., 56., 86., 51.,  8., 65.,
       51., 68., 60., 29., 31., 91., 29., 78.,  4., 57., 79.,  9., 74.,
       22., 40., 57., 32., 60., 86., 34., 87., 94., 38., 56., 46., 55.,
        5., 80., 16., 79., 23., 54., 80., 93., 73., 76., 79., 48., 30.,
       59., 60., 53., 82., 35., 34., 19., 32., 41., 39., 92., 81., 83.,
       35., 29., 96., 21., 77., 79.,  6., 21., 44., 62., 38., 98.,  8.,
        4.,  3., 15., 94., 80., 17., 16., 81., 27.])

In [ ]:
import seaborn as sns
import pandas as pd

In [ ]:
titanic_data = sns.load_dataset('titanic')
print(f'Titanic Data: ', titanic_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
Titanic Data:  None


In [ ]:
print(titanic_data.describe())

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200


In [ ]:
print(f'Missing Values in age', titanic_data['age'].isnull().sum())

Missing Values in age 177


In [ ]:
missing_values = titanic_data['age'].isnull().sum()
print(f'Missing Values in age', missing_values)

Missing Values in age 0


In [ ]:
titanic_data['age'].fillna(titanic_data['age'].mean(), inplace=True)
titanic_data['age'].isnull().sum()

np.int64(0)

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv')

In [12]:
print(df.head())
print(df.shape)
print(df.info())
print(df.columns)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
(244, 7)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB
None
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')


In [15]:
df[df['tip'] > 5]

total_bill    tip     sex smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
44        30.40   5.60    Male     No   Sun  Dinner     4
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [20]:
df[(df['tip'] > 5) & (df['sex']=='Male')]

total_bill    tip   sex smoker   day    time  size
23        39.42   7.58  Male     No   Sat  Dinner     4
44        30.40   5.60  Male     No   Sun  Dinner     4
47        32.40   6.00  Male     No   Sun  Dinner     4
59        48.27   6.73  Male     No   Sat  Dinner     4
88        24.71   5.85  Male     No  Thur   Lunch     2
116       29.93   5.07  Male     No   Sun  Dinner     4
141       34.30   6.70  Male     No  Thur   Lunch     6
170       50.81  10.00  Male    Yes   Sat  Dinner     3
172        7.25   5.15  Male    Yes   Sun  Dinner     2
181       23.33   5.65  Male    Yes   Sun  Dinner     2
183       23.17   6.50  Male    Yes   Sun  Dinner     4
211       25.89   5.16  Male    Yes   Sat  Dinner     4
212       48.33   9.00  Male     No   Sat  Dinner     4
239       29.03   5.92  Male     No   Sat  Dinner     3

In [23]:
df['tip_%'] = 100 * df['tip']/df['total_bill']
print(df.head())

   total_bill   tip     sex smoker  day    time  size      tip_%
0       16.99  1.01  Female     No  Sun  Dinner     2   5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3  16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3  16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2  13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4  14.680765
